name: Update bitcero README file
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update bitcero repo's README file
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: bitcero/profile-stats@main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          COMMIT_MSG: "chore: update README file"
